name: Pipeline HTML Multi-Stage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Validar existência do HTML
        run: |
          echo "Etapa de build iniciada"
          test -f index.html
          echo "Arquivo index.html encontrado"

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Testar conteúdo da página
        run: |
          echo "Etapa de testes iniciada"
          grep "Minha primeira aplicação" index.html
          echo "Texto esperado encontrado no HTML"

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Simular deploy
        run: |
          echo "Etapa de deploy iniciada"
          echo "Aplicação HTML pronta para publicação"