name: Pipeline Microsservicos

on:
  push:
    branches:
      - main

jobs:

  usuarios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validar Servico Usuarios
        run: |
          echo "Validando servico de usuarios"
          test -f service-usuarios/index.html

  catalogo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validar Servico Catalogo
        run: |
          echo "Validando servico de catalogo"
          test -f service-catalogo/index.html

